services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./shared:/backend/shared
    environment:
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - BACKEND_RELOAD=true
      - BACKEND_LOG_LEVEL=info
      - SUPABASE_DATABASE_URL=${SUPABASE_DATABASE_URL}
    env_file:
      - ./backend/backend.env
    networks:
      - lutebard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - ./shared:/frontend/shared
      - /frontend/node_modules
    environment:
      - FRONTEND_PORT=3000
      - FRONTEND_HOST=0.0.0.0
    env_file:
      - .env
    networks:
      - lutebard-network



  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - lutebard-network

networks:
  lutebard-network:
    driver: bridge
